<?php
echo "<!DOCTYPE HTML>
<html>
   <head>
      <meta charset='utf-8'>
      <title>Login Error</title>
      <link rel='stylesheet' href='css/normalize.css'>
      <link rel='stylesheet' href='css/style.css'>
   </head>
   <body>
      <h1>Login Error</h1>
      <p>Invalid username or password. Click <a href='./index.php?action=login'>here</a> to go back to the home page and log in, or wait 5 seconds to be redirected.</p>
   </body>
</html>
";
