<?php
echo "<!DOCTYPE HTML>
<html>
   <head>
      <meta charset='utf-8'>
      <title>Registration Error</title>
      <link rel='stylesheet' href='css/normalize.css'>
      <link rel='stylesheet' href='css/style.css'>
   </head>
   <body>
      <h1>Registration Error</h1>
      <p>It appears as though the username with which you’re trying to register already exists. Click <a href='./index.php?action=register'>here</a> to go back and try again, or you can wait 8 seconds to be redirected.</p>
   </body>
</html>
";
